export const ENDPOINTS = {
  DASHBOARD: '/dashboard',
  LOGIN: '/login',
  REGISTER: '/register',
  TRANSACTIONS: '/transactions',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  SEND_MONEY: '/send-money',
  REQUEST_MONEY: '/request-money',
  TRANSACTION_HISTORY: '/transaction-history',
  EXPORT: '/export',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  TWO_FACTOR: '/2fa',
  SECURITY_SETTINGS: '/security-settings',
  PAYMENT_METHODS: '/payment-methods',
  CURRENCY_SETTINGS: '/currency-settings',
  API: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/register',
    LOGOUT: '/api/auth/logout',
    RESET_PASSWORD: '/api/auth/reset-password',
    VERIFY_EMAIL: '/api/auth/verify-email',
    SEND_MONEY: '/api/transactions/send',
    REQUEST_MONEY: '/api/transactions/request',
    TRANSACTIONS: '/api/transactions',
    PROFILE: '/api/user/profile',
    SETTINGS: '/api/user/settings',
    NOTIFICATIONS: '/api/notifications',
    EXPORT: '/api/export',
    CURRENCIES: '/api/currencies',
    PAYMENT_METHODS: '/api/payment-methods'
  }
}; 